#configuration file

model: Basic
num_epochs: 5
batch_size: 512
learning_rate: 0.0001
reg: 0.0
dropout: 0
data_dir: 'data/'
exp_dir: 'experiment_1/'
data_dim: [6]
num_classes: 4
test: True
train: True

